package com.yogisn.foods

object FoodsData {
    private val foodsNames = arrayOf(
        "Sate",
        "Soto Kudus",
        "Gado-gado",
        "Asinan Bogor",
        "Kerak Telor",
        "Rujak Buah",
        "Rendang",
        "Nasi Goreng",
        "Pempek",
        "Gudeg",
        "Selat Solo",
        "Rawon",
        "Bebek Betutu",
        "Surabi",
        "Nasi Campur Bali"
    )

    private val foodsDetails = arrayOf(
        "Bagi masyarakat Indonesia, sate bukalah masakan yang asing di telinga. Umumnya, sate terbuat dari potongan daging ayam, sapi, kambing, dan kelinci. Menu makanan yang satu ini diperkirakan muncul dari para pedagang jalanan di sekitar Pulau Jawa pada abad ke-19. Faktanya, sate mulai populer bersamaan dengan kedatangan para pedagang Arab, Gujarat India, dan para pedagang Muslim di Pulau Jawa lainnya. \n Di Tanah Air terdapat tiga menu sate yang cukup terkenal, yaitu Sate Madura, Sate Padang, dan Sate lilit.",
        "Suka dengan makanan berkuah yang segar? Yuk, cicipi kuliner khas Indonesia yang bernama soto Kudus. Soto yang berasal dari Kudus, Jawa Tengah ini merupakan soto dengan suwiran daging ayam atau kerbau. Pilihan daging kerbau digunakan karena masyarakat Kudus sangat menghormati kepercayaan umat Hindu yang menyucikan sapi.\n Umumnya, soto kudus disajikan bersama dengan suwiran daging ayam atau kerbau. Biasanya ditemani dengan bahan pelengkap, seperti kuah yang dilengkapi dengan tauge dan irisan seledri yang dimasukkan ke dalam mangkuk kecil. Aroma kuahnya yang berbeda dari soto Betawi maupun soto Bogor datang dari jintan, bumbu halus penyedap yang ditambahkan untuk menggugah selera. \n Jika kamu sedang berada di Kota Kudus, tak ada salahnya apabila kamu mencicipi kuliner khas sotonya. Dengan merogoh kocek Rp 8.000-Rp 25.000 kamu sudah bisa menikmati semangkok soto yang menyegarkan. Tak ingin jauh-jauh datang ke Kudus, kamu bisa membuat soto Kudus sendiri di rumah.",
        "Gado-gado, menu makanan Indonesia ini sangat terkenal dari Sabang hingga Merauke. Salah satu kejuaraan memasak internasional Napoli tahun 2010 menobatkan gado-gado sebagai masakan yang menampilkan sajian estetika. Nama gado-gado tak tercantum di kamus Bahasa Indonesia mau pun Betawi. Namun nama ini melahirkan banyak istilah, salah satunya yang memiliki arti \"campur aduk\". \n Gado-gado biasa disajikan bersama potongan lontong atau nasi. Tampilannya sepintas memang mirip Lotek Jawa Tengah dan Pecel Jawa Timur namun terdapat perbedaan signifikan. Gado-gado tak menggunakan kencur dalam bumbu kacangnya dan menggunakan sayuran, telur, tahu, tempe, lontong, dan toping lain. \n Selain nikmat dipandang, rasanya juga tak kalah enak kok! Sayuran yang disiram bumbu kacang dan ditaburi bawang goreng, serta emping adalah paduan yang sangat sempurna. Kandungan gizi gado-gado terbilang lengkap, mulai dari vitamin, mineral, hingga protein. Sayuran hijau yang berserat di dalamnya bermanfaat untuk mencegah penyakit degeneratif, seperti jantung, batu empedu, hingga kanker.",
        "Asinan Bogor, makanan yang tebuat dari aneka sayur dan buah segar yang diambah tempe dan tahu gireng, kerupuk, dan kacang goreng ini tak pernah sepi penggemar. Asinan tersebut dibuat dengan cara pengasinan buah dan sayur dengan garam atau pengasaman menggunakan cuka dan cabai rawit. Mengacu dari cara pembuatannya, asinan Bogor menggunakan proses pengawetan sayur dan buah menggunakan cara alami. \n Hidangan khas Bogor yang satu ini mengandung zat anti mikroba dan antioksidan yang sangat bermanfaat untuk menangkal kanker dan hipertensi. Selain itu, asinan bogor mampu membantu pencegahan osteoporosis dan menjadikan wajahmu lebih awet muda. asinan Bogor memiliki tiga varian, yaitu asinan buah, sayur, dan campuran. Ketiganya memiliki rasa campuran yang, pedas, asam, dan manis. \n Biasa dijajakan oleh pedagang kaki lima, asinan Bogor sangat cocok dinikmati di siang hari. Meskipun demikian makanan ini bisa disajikan hangat atau dingin. Untuk varian yang dingin, kamu akan menikmatinya dengan campuran es yang akan menambah kesegaran kuah asinannya. Kuah memegang peranan penting dalam rasa asinan. Kombinasi rasa yang sempurna antara manis, asam, dan pedas disatukan dengan buah segar.",
        "Ibu kota punya kerak telor khas Betawi sebagai makanan tradisionalnya. Berbahan dasar telur bebek atau ayam, yang dicampur dengan beras ketan, serundeng, udang, bawang goreng, dan bumbu lain. Kerak telor memiliki rasa gurih dan manis yang menggoyang lidahmu. Harganya pun sangat terjangkau, dipatok dengan harga Rp 10.000 hingga Rp 15.000. Kerak telor sangat mudah ditemui di berbagai food court atau stand makanan di obyek wisata maupun event-event besar, seperti Pekan Raya Jakarta dan Jakarta Fair. \n Kerak telor mulai diperkenalkan tahun 1970 saat Jakarta masih bernama Batavia. Dijajakan oleh penduduk Betawi di kawasan Monas saat itu, kerak telor menjadi daya tarik setiap orang yang ke sana.",
        "Menu tradisional berbahan dasar buah-buahan berikut datang dari Pulau Jawa. Aneka menu rujak tersedia disini, mulai dari Rujak Cemplung, Rujak Letok, Rucak Kecut, hingga Rujak Dulit. Meskipun bukan termasuk makanan pengenyang perut, rujak-rujak ini wajib kamu cicipi.\n Penamaan masing-masing rujak akan membedakan adalah cara mengiris buahnya. Rujak dulit artinya 'dicolek' sehingga buahnya sangat cocok dipotong miring. Rujak Kecut atau asam memiliki rasa yang asam namun segar. Rujak Cemplung artinya 'dimasukkan' sehingga buah dengan potongan dadu sangat pas apabila langsung dimasukkan ke dalam bumbu.\n Selain aneka rujak di atas, ternyata masih ada lagi rujak yang lainnya. Rujak Kuah Pindang, rujak berisi potongan buah segar yang disajikan bersama dengan kuah encer yang terbuat dari bahan ikan, garam, terasi, dan cabai. Selanjutnya adalah Rujak Bebeg. Rujak ini dibuat dengan cara dilumatkan atau semua bahan ditumbuk bersama dengan bumbunya. Dan yang terakhir adalah Rujak Gobet. Rujak ini berbahan dasar buah mangga, timun, dan kedondong serut yang dicampur dengan gula aren dan asam jawa.",
        "Dinobatkan sebagai makanan paling lezat di seluruh dunia, rendang Padang ternyata masuk dalam makanan yang sulit dibuat. Kaya akan rempah membuatnya sangat nikmat dan menggiurkan. Selain sulit, waktu yang diperlukan untuk memasaknya juga cukup lama. Aneka campuran, seperti santan, rempah-rempah lain yang telah dihaluskan seperti cabai, serai, lengkuas, kunyit, jahe, bawang putih, dan bawang merah tak boleh sampai salah takaran.\n Sebenarnya rendang merupakan teknik memasak dan mengawetkan daging dengan merendamnya ke dalam santan yang disertai rempah-rempah. Diperkirakan sudah berusia ratusan tahun, masakan asli Minangkabau ini punya arti yang sangat mendalam bagi masyarakatnya. Menu makanan ini selalu disajikan saat upacara adat Bajamba Gadang atau pesta makan besar bersama dalam rangka pengukuhan dan pengakuan seorang datuk di daerahnya.\n Berdasarkan budaya dan pandangan filsuf, rendang dipandang sebagai tiga komposisi paten dalam suatu pemerintahan yang dianggap terhormat. Daging sapi sebagai bahan utama melambangkan kepala adat atau ketua suku (niniak mamak) dan ibu (bundo kanduang) yang memberi kemakmuran.\n Kelapa atau karambia melambangkan kaum cerdas, cerdik, serta pandai atau intelek. Dan yang terakhir adalah cabai atau labo melambangkan alim ulama yang tegas untuk mengajak masyarakat pada agama atau syarak.",
        "Bagi orang Indonesia, nasi goreng adalah menu makanan yang sangat ikonik. Ajang “World Expo Shanghai China 2010” menobatkannya menjadi suguhan menarik yang semakin dikenal di mata dunia.\n Nasi goreng sendiri sudah lahir sekitar 4000 tahun sebelum Masehi. Berasal dari kebiasaan masyarakat Tionghoa yang tak menyukai makanan dingin, nasi goreng kini mulai mendunia. Banyaknya masyarakat Tionghoa yang merantau ke daerah lain, membuat menu nasi goreng yang dibuat oleh mereka menggunakan bumbu dan variasi bahan makanan yang ada di sekitar tempat tinggalnya.\n Di Indonesia terdapat beberapa jenis nasi goreng yang kini jumlahnya terus bertambah. Meskipun variasi dan bumbunya yang terus dikreasikan, menu tersebut tetaplah menggunakan nasi sebagai bahan utamanya. Nah, berikut ini merupakan resep nasi goreng Jawa yang dapat kamu buat di rumah.",
        "Pempek, makanan khas Palembang yang satu ini berbahan dasar ikan. Diolah bersama dengan tepung, rasa makanan ini cenderung gurih pada pempeknya dan asam manis pada sausnya. Kuah encer yang digunakan sebagai saus pempek adalah perpaduan antara gula dan saus cuka.\n Awalnya pempek dikenal dengan nama 'kalesan', alat yang digunakan untuk menghaluskan daging ikan. Alat ini berbentuk cembung dengan tambahan kuping di sisi yang berhadapan. Pembuatannya yang mengunakan teknik ditekan tekan atau di-'keles' membuat pempek dikenal dengan nama lain yakni \"kalesan\".\n Bahan dasar ikan yang digunakan oleh pempek dahulu adalah ikan belida. Seiring berjalannya waktu, ikan tersebut menjadi langka dan dihargai sangat mahal. Hal ini membuat masyarakat beralih menggunakan ikan yang lebih murah dan mudah diperoleh. Pempek memiliki banyak jenis dengan rasa yang berbeda, antara lain: Pempek Lenjer, Pempek Keriting, Pempek Tahu, Pempek Kapal Selam, Pempek Pistel, Pempek Adaan, Pempek Kulit, Pempek Telor (Telok), Pempek Panggang (tunu), dan Pempek Lenggang.\n Jenis pempek yang paling terkenal adalah Kapal Selam yang terbuat dari telur ayam yang dibungkus dengan adonan Pempek dan digoreng dalam minyak panas. Pempek lainnya adalah Pistel yang berisi irisan pepaya muda rebus yang dibumbui. Tak perlu jauh-jauh ke Palembang, kamu bisa menikmatinya sendiri di rumah.",
        "Belum lengkap namanya, jika datang ke Yogyakarta tanpa mencicipi gudeg. Menu makanan berbahan dasar nangka muda ini memiliki aroma yang harum dan rasa yang nikmat ketika disantap. Gudeg Jogja biasanya menggunakan kuali sebagai media masaknya.\n Sejarah Gudeg Jogja hadir besamaan dengan munculnya Kerajaan Mataram Islam di Alas Mentaok Kota Gede pada tahun 1500. Di abad ke-19, makanan ini belum banyak dijual karena proses memasaknya yang lama. Tahun 1940-an Gudeg mulai populer, terutama saat Presiden Soekarno membangun Universitas Gajah Mada (UGM) Yogyakarta.\n Beberapa jenis Gudeg yang bisa kamu temui, antara lain: gudeg kering, basah, khas Yogyakarta, khas Solo, dan khas Jawa Timur. Untuk gudeg kering, santan yang digunakan lebih sedikit, sedangkan gudeg basah sebaliknya. Gudeg Yogyakarta memiliki rasa lebih manis, lebih kering, dan berwarna lebih merah. Gudeg Solo atau Surakarta lebih berair dam pekat dengan jumlah santan dan warna lebih putih dan cerah. Gudeg Jawa Timur memiliki rasa lebih pedas dan panas dibandingkan gudeg-gudeg lainnya.\n Di balik rasanya yang sangat nikmat, pembuatan Gudeg memang membutuhkan waktu yang sangat lama.",
        "Selat Solo atau lebih dikenal dengan nama bistik jawa merupakan menu modifikasi daging yang dimasak seperti demur. Dilengkapi dengan kentang goreng, selada, acar mentimun, putih telur rebus, buncis, dan wortel iris rebus, bistik ini kemudian disiram dengan kuah kecokelatan dengan rasa yang manis. Selain saus yang menyerupai semur, Selat Solo juga menggunakan kuning telur yang dimasak dan dicampur dengan mustard. Rasanya mustard kuning telur ini cenderung asam.\n Makanan khas Solo ini merupakan peninggalan zaman kolonial Hindia Belanda. Diadopsi dari masakan bernama Salachtje, Selat Solo muncul berkat kreasi orang Jawa.",
        "Menggunakan kluwek, makanan khas Jawa Timur ini memiliki kuah hitam yang sangat menyegarkan. Rawon, sup daging dengan kuah hitam yang berasal dari bumbunya wajib kamu coba. Kluwek atau biji kepayang yang baik digunakan untuk Rawon adalah yang berwarna hitam atau kemerahan. Daging yang digunakan pun adalah daging sapi khusus rawonan.\n Sangat populer di Kota Surabaya, rawon sekarang ini sudah tersebar di berbagai wilayah di Indonesia. Rasanya yang sangat nikmat membuatnya mudah diterima oleh masyarakat. Dagingnya yang empuk dengan perpaduan rasa manis, gurih, dan legit pada kuahnya siap menggoyang lidahmu. Aroma dan rasanya yang pekat tak bisa lepas dari pengaruh bumbu kluwek yang digunakannya.",
        "Selain kaya akan tempat wisata, Bali juga menyimpan kuliner tradisional yang sangat nikmat. Bebek dan ayam Betutu adalah salah satunya. Gilimanuk merupakan daerah yang terkenal dengan menu olahan betutu pedasnya, sedangkan Gianyar menyediakan betutu dengan rasa yang lebih pedas dan gurih.\n Betutu memiliki dua tipe bumbu yaitu base genep atau bumbu lengkap dan base wangen atau bumbu harum. Pembuatan Betutu Gianyar lebih sulit karena menggunakan tambahan berupa upih atau pelepah pinang. Kuliner yang satu ini memiliki daging yang empuk dan tekstur ayam atau bebek panggang dengan bumbu rempah yang akan menggugah selera makanmu.\n Awalnya, bebek Betutu merupakan menu makanan seremonial yang dimasak dalam waktu lama. Lebih dari lima belas bumbu digunakan untuk menghasilkan makanan tradisional yang satu ini. Selain tampilannya yang indah, bebek dan ayam betutu kerap kali digunakan sebagai sajian pada upacara keagamaan umat Hindu di Pulau Bali.",
        "Serabi merupakan makanan asal Sunda yang berasal dari kata 'sura' yang berarti 'besar'. Sejak tahun 1920-an, serabi menjadi jajanan pasar yang cukup terkenal. Awalnya makanan tradisional ini disajikan dengan gula jawa dan santan namun seiring berkembangnya zaman, banyak jenis serabi modifikasi yang wajib kamu coba.\n Jajanan pasar asal Sunda tersebut memiliki bentuk layaknya panekuk atau pancake dengan ukuran yang lebih kecil dan tebal. Biasanya cara pembuatannya adalah dibakar menggunakan alat tradisional, seperti tungku dan cetakan dari tanah liat namun sekarang sudah sedikit berbeda.\n Meskipun berasal dari Sunda, Solo adalah salah satu kota dengan penjual Serabi yang cukup banyak dan terkenal. Serabi Notokusuman merupakan serabi yang paling terkenal di Kota Solo, Berdiri sejak tahun 1923, daerah dengan nama Notokusuman menjadi pusat para penjual Serabi terkenal. Sepertinya tak hanya Solo, Sumatera Barat dan Sumatera Utara juga punya menu Serabi Durian yang sangat nikmat.",
        "Sepertinya tak hanya Bebek Betutu saja yang terkenal sebagai kuliner khas Bali. Nasi Campur Bali, menu khas yang satu ini bersisi nasi, ayam kampung betutu suwir, urapan, sambal matah, sambal goreng, telor pindang, kulit ayam, beberapa seafood yang juga disertakan sate lilit yang sangat nikmat. Paduan rasa yang seimbang membuatnya menjadi makanan yang wajib kamu cicip saat berlibur ke Bali.\n Salah satu tempat makan yang menyediakan Nasi Campur yang sangat lezat adalah Nasi Campur Men Weti yang berada di pantai Sindhu Sanur dan Warung adik dari Men Wati. Para penjual biasanya membanderolnya dengan harga Rp 25.000/porsinya."
    )

    private val foodsImages = intArrayOf(
        R.drawable.sate,
        R.drawable.soto_kudus,
        R.drawable.gado_gado,
        R.drawable.asinan_bogor,
        R.drawable.kerak_telor,
        R.drawable.rujak_buah,
        R.drawable.rendang,
        R.drawable.nasi_goreng,
        R.drawable.pempek,
        R.drawable.gudeg,
        R.drawable.selat_solo,
        R.drawable.rawon,
        R.drawable.bebek_betutu,
        R.drawable.surabi,
        R.drawable.nasi_campur_bali
    )

    val lisData: ArrayList<Foods>
    get() {
        val list = arrayListOf<Foods>()
        for(position in foodsNames.indices){
            val foods = Foods()
            foods.gambar = foodsImages[position]
            foods.name = foodsNames[position]
            foods.detail = foodsDetails[position]
            list.add(foods)
        }
        return list
    }
}